source("./graph_hw.R")
library(testthat)

liona <- read.csv("https://raw.githubusercontent.com/mydatastory/textbooks/master/_moore/data/lionCrater.csv")
rhinoa <- read.csv("https://raw.githubusercontent.com/mydatastory/textbooks/master/_moore/data/blackRhinoCrater.csv")
dataa <- c(min(liona$Population), min(rhinoa$Population))
names(dataa) <- c("Lion", "Rhino")
lion2a <- subset(liona, liona$Year > 1979)
rhino2a <- subset(rhinoa, rhinoa$Year < 1993)

test_that("hw answers", {
  
  expect_equal(lion, liona)
  expect_equal(rhino, rhinoa)
  expect_equal(lion_pop_plot, plot(liona$Year, liona$Population, main="Lion Population", xlab="Year", ylab="Population"))
  expect_equal(rhino_pop_plot, plot(rhinoa$Year, rhinoa$Population, main="Rhino Population", xlab="Year", ylab="Population", col="darkgreen", type="l", lty=2))
  expect_equal(q3_Constant, F)
  expect_equal(q3_Only_decreasing, F)
  expect_equal(q3_Increasing_then_decreasing, T)
  expect_equal(q3_Only_increasing, F)
  expect_equal(q3_Decreasing_then_increasing, F)
  expect_equal(q4_Constant, F)
  expect_equal(q4_Only_decreasing, F)
  expect_equal(q4_Increasing_then_decreasing, F)
  expect_equal(q4_Only_increasing, F)
  expect_equal(q4_Decreasing_then_increasing, T)
  expect_equal(direct, F)
  expect_equal(inverse, T)
  expect_equal(answer6, par(mfrow=c(2,1)))
  dev.off()
  expect_equal(lion2, lion2a)
  expect_equal(rhino2, rhino2a)
  expect_equal(answer8, plot(lion2a$Year, lion2a$Population, type = "l", col = "purple", main = "Lion and Black Rhino Population", xlab = "Year", ylab = "Population", ylim = c(0,100)))
  expect_equal(answer8_added_points, points(rhino2a$Year, rhino2a$Population, col = "red"))
  expect_equal(answer9, legend("topright", legend = c("Lion", "Black Rhino"), col = c("purple", "red"), lty = c(1,NA), pch = c(NA,1)))
  expect_equal(data, dataa)
  expect_equal(names(data), c("Lion", "Rhino"))
  expect_equal(answer10, barplot(dataa))
  expect_equal(answer11, boxplot(liona$Population, rhinoa$Population, names = c("Lion", "Rhino"), main = "Population Sizes"))
  expect_equal(answer12, hist(rhino$Population, main = "Rhino Population Sizes", xlab = "Population Size"))
  expect_equal(answer13, abline(v=mean(rhinoa$Population), col = "orange"))
  
})
